plugins {
    id "com.gradleup.shadow" version "9.4.2"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

repositories {
    maven { url "https://maven.terraformersmc.com/releases/" }
    mavenCentral()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    minecraft "net.minecraft:minecraft:${rootProject.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    api "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    api "dev.architectury:architectury-fabric:${rootProject.architectury_api_version}"
    api "com.terraformersmc:modmenu:${rootProject.modmenu_version}"
    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

processResources {
    def props = [
            "version": project.version,
            "minecraft_version": rootProject.minecraft_version,
            "min_minecraft_version": rootProject.min_minecraft_version,
            "fabric_loader_version": rootProject.fabric_loader_version,
            "architectury_api_version": rootProject.architectury_api_version,
            "java_version": rootProject.java_version
    ]
    inputs.properties props

    filesMatching("fabric.mod.json") {
        expand props
    }
}

shadowJar {
    dependsOn jar
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    zip64 = true
}

assemble.dependsOn shadowJar

jar {
    archiveClassifier = "dev"
}