# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version=1.0.4
maven_group=net.vg
archives_name=structurablevoid
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=26.1.2
min_minecraft_version=26.1
official_mappings=true

# Dependencies
architectury_api_version=20.0.6
fabric_loader_version=0.19.2
fabric_api_version=0.150.0+26.1.2
neoforge_version=26.1.2.76
min_neoforge_version=26.1.2.70
java_version=25

# ModMenu version (for Fabric only)
modmenu_version=18.0.0-beta.1