modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "structurablevoid"
version = "${version}"
displayName = "Structurable Void"
authors = "VgLevelUp, StarmanMine142"
description = '''
Client side mod to make using the block Structure Void easier.
'''

[[dependencies.structurablevoid]]
modId = "neoforge"
type = "required"
versionRange = "[${min_neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.structurablevoid]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.structurablevoid]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "structurablevoid.mixins.json"