plugins {
    id "com.gradleup.shadow" version "9.4.2"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"
    minecraft "net.minecraft:minecraft:${rootProject.minecraft_version}"
    implementation "dev.architectury:architectury-neoforge:${rootProject.architectury_api_version}"
    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ':common', configuration: 'transformProductionNeoForge')) { transitive false }
}

processResources {
    def resourceTargets = [
            'version': project.version,
            'minecraft_version': rootProject.minecraft_version,
            'neoforge_version': rootProject.neoforge_version,
            'min_neoforge_version': rootProject.min_neoforge_version,
            'java_version': rootProject.java_version,
            'architectury_api_version': rootProject.architectury_api_version
    ]
    inputs.properties resourceTargets

    filesMatching('META-INF/neoforge.mods.toml') {
        expand resourceTargets
    }
}

shadowJar {
    dependsOn jar
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    zip64 = true
}

assemble.dependsOn shadowJar

jar {
    archiveClassifier = "dev"
}